// <auto-generated />
using System;
using AirFlight2.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirFlight2.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240604093704_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirFlight2.Entities.Models.AirPort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AirPortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("AirPorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirPortName = "Şakirpaşa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4246)
                        },
                        new
                        {
                            Id = 2,
                            AirPortName = "Ankara Esenboğa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4258)
                        },
                        new
                        {
                            Id = 3,
                            AirPortName = "Antalya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4259)
                        },
                        new
                        {
                            Id = 4,
                            AirPortName = "Gazipaşa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4260)
                        },
                        new
                        {
                            Id = 5,
                            AirPortName = "Balıkesir Koca Seyit Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4261)
                        },
                        new
                        {
                            Id = 6,
                            AirPortName = "Bursa Yenişehir Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4262)
                        },
                        new
                        {
                            Id = 7,
                            AirPortName = "Çanakkale Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4263)
                        },
                        new
                        {
                            Id = 8,
                            AirPortName = "Denizli Çardak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4264)
                        },
                        new
                        {
                            Id = 9,
                            AirPortName = "Diyarbakır Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4265)
                        },
                        new
                        {
                            Id = 10,
                            AirPortName = "Elazığ Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4266)
                        },
                        new
                        {
                            Id = 11,
                            AirPortName = "Erzurum Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4267)
                        },
                        new
                        {
                            Id = 12,
                            AirPortName = "Hasan Polatkan Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4268)
                        },
                        new
                        {
                            Id = 13,
                            AirPortName = "Gaziantep Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4269)
                        },
                        new
                        {
                            Id = 14,
                            AirPortName = "Hatay Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4270)
                        },
                        new
                        {
                            Id = 15,
                            AirPortName = "Isparta Süleyman Demirel Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4271)
                        },
                        new
                        {
                            Id = 16,
                            AirPortName = "İstanbul Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4272)
                        },
                        new
                        {
                            Id = 17,
                            AirPortName = "Sabiha Gökçen Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4274)
                        },
                        new
                        {
                            Id = 18,
                            AirPortName = "Adnan Menderes Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4275)
                        },
                        new
                        {
                            Id = 19,
                            AirPortName = "Kars Harakani Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4276)
                        },
                        new
                        {
                            Id = 20,
                            AirPortName = "Erkilet Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4277)
                        },
                        new
                        {
                            Id = 21,
                            AirPortName = "Cengiz Topel Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4278)
                        },
                        new
                        {
                            Id = 22,
                            AirPortName = "Konya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4279)
                        },
                        new
                        {
                            Id = 23,
                            AirPortName = "Zafer Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4280)
                        },
                        new
                        {
                            Id = 24,
                            AirPortName = "Malatya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4281)
                        },
                        new
                        {
                            Id = 25,
                            AirPortName = "Dalaman Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4282)
                        },
                        new
                        {
                            Id = 26,
                            AirPortName = "Milas-Bodrum Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4283)
                        },
                        new
                        {
                            Id = 27,
                            AirPortName = "Nevşehir Kapadokya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4284)
                        },
                        new
                        {
                            Id = 28,
                            AirPortName = "Ordu-Giresun Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4285)
                        },
                        new
                        {
                            Id = 29,
                            AirPortName = "Rize-Artvin Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4286)
                        },
                        new
                        {
                            Id = 30,
                            AirPortName = "Samsun Çarşamba Havalimanı	",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4288)
                        },
                        new
                        {
                            Id = 31,
                            AirPortName = "Sinop Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4289)
                        },
                        new
                        {
                            Id = 32,
                            AirPortName = "Sivas Nuri Demirağ Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4290)
                        },
                        new
                        {
                            Id = 33,
                            AirPortName = "Şanlıurfa GAP Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4291)
                        },
                        new
                        {
                            Id = 34,
                            AirPortName = "Tekirdağ Çorlu Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4292)
                        },
                        new
                        {
                            Id = 35,
                            AirPortName = "Trabzon Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4293)
                        },
                        new
                        {
                            Id = 36,
                            AirPortName = "Uşak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4294)
                        },
                        new
                        {
                            Id = 37,
                            AirPortName = "Van Ferit Melen Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4295)
                        },
                        new
                        {
                            Id = 38,
                            AirPortName = "Zonguldak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 12, 37, 4, 249, DateTimeKind.Local).AddTicks(4296)
                        });
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 2,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.AirPort", b =>
                {
                    b.HasOne("AirFlight2.Entities.Models.Country", "Country")
                        .WithMany("AirPorts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.Country", b =>
                {
                    b.Navigation("AirPorts");
                });
#pragma warning restore 612, 618
        }
    }
}
