// <auto-generated />
using System;
using AirFlight2.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirFlight2.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240604171831_initial4")]
    partial class initial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirFlight2.Entities.Models.AirPort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AirPortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("AirPorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirPortName = "Şakirpaşa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2209)
                        },
                        new
                        {
                            Id = 2,
                            AirPortName = "Ankara Esenboğa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2220)
                        },
                        new
                        {
                            Id = 3,
                            AirPortName = "Antalya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2222)
                        },
                        new
                        {
                            Id = 4,
                            AirPortName = "Gazipaşa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2223)
                        },
                        new
                        {
                            Id = 5,
                            AirPortName = "Balıkesir Koca Seyit Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2224)
                        },
                        new
                        {
                            Id = 6,
                            AirPortName = "Bursa Yenişehir Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2225)
                        },
                        new
                        {
                            Id = 7,
                            AirPortName = "Çanakkale Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2227)
                        },
                        new
                        {
                            Id = 8,
                            AirPortName = "Denizli Çardak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2228)
                        },
                        new
                        {
                            Id = 9,
                            AirPortName = "Diyarbakır Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2229)
                        },
                        new
                        {
                            Id = 10,
                            AirPortName = "Elazığ Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2231)
                        },
                        new
                        {
                            Id = 11,
                            AirPortName = "Erzurum Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2232)
                        },
                        new
                        {
                            Id = 12,
                            AirPortName = "Hasan Polatkan Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2233)
                        },
                        new
                        {
                            Id = 13,
                            AirPortName = "Gaziantep Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2235)
                        },
                        new
                        {
                            Id = 14,
                            AirPortName = "Hatay Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2236)
                        },
                        new
                        {
                            Id = 15,
                            AirPortName = "Isparta Süleyman Demirel Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2237)
                        },
                        new
                        {
                            Id = 16,
                            AirPortName = "İstanbul Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2239)
                        },
                        new
                        {
                            Id = 17,
                            AirPortName = "Sabiha Gökçen Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2240)
                        },
                        new
                        {
                            Id = 18,
                            AirPortName = "Adnan Menderes Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2241)
                        },
                        new
                        {
                            Id = 19,
                            AirPortName = "Kars Harakani Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2243)
                        },
                        new
                        {
                            Id = 20,
                            AirPortName = "Erkilet Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2244)
                        },
                        new
                        {
                            Id = 21,
                            AirPortName = "Cengiz Topel Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2245)
                        },
                        new
                        {
                            Id = 22,
                            AirPortName = "Konya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2247)
                        },
                        new
                        {
                            Id = 23,
                            AirPortName = "Zafer Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2248)
                        },
                        new
                        {
                            Id = 24,
                            AirPortName = "Malatya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2249)
                        },
                        new
                        {
                            Id = 25,
                            AirPortName = "Dalaman Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2250)
                        },
                        new
                        {
                            Id = 26,
                            AirPortName = "Milas-Bodrum Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2252)
                        },
                        new
                        {
                            Id = 27,
                            AirPortName = "Nevşehir Kapadokya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2253)
                        },
                        new
                        {
                            Id = 28,
                            AirPortName = "Ordu-Giresun Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2255)
                        },
                        new
                        {
                            Id = 29,
                            AirPortName = "Rize-Artvin Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2256)
                        },
                        new
                        {
                            Id = 30,
                            AirPortName = "Samsun Çarşamba Havalimanı	",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2257)
                        },
                        new
                        {
                            Id = 31,
                            AirPortName = "Sinop Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2258)
                        },
                        new
                        {
                            Id = 32,
                            AirPortName = "Sivas Nuri Demirağ Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2260)
                        },
                        new
                        {
                            Id = 33,
                            AirPortName = "Şanlıurfa GAP Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2261)
                        },
                        new
                        {
                            Id = 34,
                            AirPortName = "Tekirdağ Çorlu Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2262)
                        },
                        new
                        {
                            Id = 35,
                            AirPortName = "Trabzon Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2264)
                        },
                        new
                        {
                            Id = 36,
                            AirPortName = "Uşak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2265)
                        },
                        new
                        {
                            Id = 37,
                            AirPortName = "Van Ferit Melen Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2266)
                        },
                        new
                        {
                            Id = 38,
                            AirPortName = "Zonguldak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2267)
                        },
                        new
                        {
                            Id = 39,
                            AirPortName = "Merzbrück Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2269)
                        },
                        new
                        {
                            Id = 40,
                            AirPortName = "Leipzig-Altenburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2270)
                        },
                        new
                        {
                            Id = 41,
                            AirPortName = "Augsburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2271)
                        },
                        new
                        {
                            Id = 42,
                            AirPortName = "Baden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2273)
                        },
                        new
                        {
                            Id = 43,
                            AirPortName = "Berlin Schönefeld Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2274)
                        },
                        new
                        {
                            Id = 44,
                            AirPortName = "Berlin Tegel Havalimanı ",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2275)
                        },
                        new
                        {
                            Id = 45,
                            AirPortName = "Bindlacher Berg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2277)
                        },
                        new
                        {
                            Id = 46,
                            AirPortName = "Borkum Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2278)
                        },
                        new
                        {
                            Id = 47,
                            AirPortName = "Braunschweig Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2279)
                        },
                        new
                        {
                            Id = 48,
                            AirPortName = "Bremerhaven Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2280)
                        },
                        new
                        {
                            Id = 49,
                            AirPortName = "Dortmund Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2282)
                        },
                        new
                        {
                            Id = 50,
                            AirPortName = "Dresden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2283)
                        },
                        new
                        {
                            Id = 51,
                            AirPortName = "Düsseldorf Uluslararası Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2284)
                        },
                        new
                        {
                            Id = 52,
                            AirPortName = "Düsseldorf-Mönchengladbach Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2286)
                        },
                        new
                        {
                            Id = 53,
                            AirPortName = "Frankfurt Egelsbach Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2287)
                        },
                        new
                        {
                            Id = 54,
                            AirPortName = "Emden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2288)
                        },
                        new
                        {
                            Id = 55,
                            AirPortName = "Erfurt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2290)
                        },
                        new
                        {
                            Id = 56,
                            AirPortName = "Frankfurt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2291)
                        },
                        new
                        {
                            Id = 57,
                            AirPortName = "Friedrichshafen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2292)
                        },
                        new
                        {
                            Id = 58,
                            AirPortName = "Giebelstadt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2294)
                        },
                        new
                        {
                            Id = 59,
                            AirPortName = "Frankfurt-Hahn Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2295)
                        },
                        new
                        {
                            Id = 60,
                            AirPortName = "Hamburg Finkenwerder Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2296)
                        },
                        new
                        {
                            Id = 61,
                            AirPortName = "Hamburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2298)
                        },
                        new
                        {
                            Id = 62,
                            AirPortName = "Hannover-Langenhagen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2299)
                        },
                        new
                        {
                            Id = 63,
                            AirPortName = "Heide-Büsum Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2300)
                        },
                        new
                        {
                            Id = 64,
                            AirPortName = "Uetersen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2301)
                        },
                        new
                        {
                            Id = 65,
                            AirPortName = "Helgoland Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2303)
                        },
                        new
                        {
                            Id = 66,
                            AirPortName = "Heringsdorf Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2304)
                        },
                        new
                        {
                            Id = 67,
                            AirPortName = "Hof-Plauen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2305)
                        },
                        new
                        {
                            Id = 68,
                            AirPortName = "Hoppstädten-Weiersbach Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2307)
                        },
                        new
                        {
                            Id = 69,
                            AirPortName = "Ingolstadt Manching Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2308)
                        },
                        new
                        {
                            Id = 70,
                            AirPortName = "Kassel Calden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2310)
                        },
                        new
                        {
                            Id = 71,
                            AirPortName = "Kiel Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2311)
                        },
                        new
                        {
                            Id = 72,
                            AirPortName = "Köln Bonn Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2313)
                        },
                        new
                        {
                            Id = 73,
                            AirPortName = "Black Forest Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2314)
                        },
                        new
                        {
                            Id = 74,
                            AirPortName = "Leipzig/Halle Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2316)
                        },
                        new
                        {
                            Id = 75,
                            AirPortName = "Lübeck Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2319)
                        },
                        new
                        {
                            Id = 76,
                            AirPortName = "Magdeburg-Cochstedt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2320)
                        },
                        new
                        {
                            Id = 77,
                            AirPortName = "Mainz-Finthen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2354)
                        },
                        new
                        {
                            Id = 78,
                            AirPortName = "Mannheim City Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2356)
                        },
                        new
                        {
                            Id = 79,
                            AirPortName = "Memmingen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2357)
                        },
                        new
                        {
                            Id = 80,
                            AirPortName = "Münih Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2359)
                        },
                        new
                        {
                            Id = 81,
                            AirPortName = "Münster Osnabrück Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2360)
                        },
                        new
                        {
                            Id = 82,
                            AirPortName = "Nannhousen Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2361)
                        },
                        new
                        {
                            Id = 83,
                            AirPortName = "Neubrandenburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2363)
                        },
                        new
                        {
                            Id = 84,
                            AirPortName = "Nürnberg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2364)
                        },
                        new
                        {
                            Id = 85,
                            AirPortName = "Paderborn Lippstadt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2365)
                        },
                        new
                        {
                            Id = 86,
                            AirPortName = "Rechlin-Lärz Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2367)
                        },
                        new
                        {
                            Id = 87,
                            AirPortName = "Rostock-Laage Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2368)
                        },
                        new
                        {
                            Id = 88,
                            AirPortName = "Saarbrücken Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2369)
                        },
                        new
                        {
                            Id = 89,
                            AirPortName = "Siegerland Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2370)
                        },
                        new
                        {
                            Id = 90,
                            AirPortName = "Stadtlohn-Vreden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2372)
                        },
                        new
                        {
                            Id = 91,
                            AirPortName = "Stuttgart Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2373)
                        },
                        new
                        {
                            Id = 92,
                            AirPortName = "Trier-Föhren Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2374)
                        },
                        new
                        {
                            Id = 93,
                            AirPortName = "Weeze Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2376)
                        },
                        new
                        {
                            Id = 94,
                            AirPortName = "Sylt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2377)
                        },
                        new
                        {
                            Id = 95,
                            AirPortName = "Zweibrücken Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2378)
                        },
                        new
                        {
                            Id = 96,
                            AirPortName = "Bremen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2380)
                        },
                        new
                        {
                            Id = 97,
                            AirPortName = "Atlanta",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2381)
                        },
                        new
                        {
                            Id = 98,
                            AirPortName = "Chicago O’Hare",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2382)
                        },
                        new
                        {
                            Id = 99,
                            AirPortName = "Los Angeles",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2383)
                        },
                        new
                        {
                            Id = 100,
                            AirPortName = "Denver",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2385)
                        },
                        new
                        {
                            Id = 101,
                            AirPortName = "Dallas/Fort Worth	",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2386)
                        },
                        new
                        {
                            Id = 102,
                            AirPortName = "New York JFK",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2387)
                        },
                        new
                        {
                            Id = 103,
                            AirPortName = "San Francisco",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2389)
                        },
                        new
                        {
                            Id = 104,
                            AirPortName = "Las Vegas",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2390)
                        },
                        new
                        {
                            Id = 105,
                            AirPortName = "Charlotte",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2391)
                        },
                        new
                        {
                            Id = 106,
                            AirPortName = "Houston Bush",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2393)
                        },
                        new
                        {
                            Id = 107,
                            AirPortName = "Miami",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2394)
                        },
                        new
                        {
                            Id = 108,
                            AirPortName = "Phoenix",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2395)
                        },
                        new
                        {
                            Id = 109,
                            AirPortName = "Orlando",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2396)
                        },
                        new
                        {
                            Id = 110,
                            AirPortName = "Seattle",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2398)
                        },
                        new
                        {
                            Id = 111,
                            AirPortName = "Minneapolis/St",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2399)
                        },
                        new
                        {
                            Id = 112,
                            AirPortName = "Newark",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2400)
                        },
                        new
                        {
                            Id = 113,
                            AirPortName = "Philadelphia",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2402)
                        },
                        new
                        {
                            Id = 114,
                            AirPortName = "Boston",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2403)
                        },
                        new
                        {
                            Id = 115,
                            AirPortName = "",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2404)
                        },
                        new
                        {
                            Id = 116,
                            AirPortName = "New York LaGuardia",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(2406)
                        });
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(4227),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(4273),
                            Name = "USA"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 20, 18, 31, 395, DateTimeKind.Local).AddTicks(4275),
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.AirPort", b =>
                {
                    b.HasOne("AirFlight2.Entities.Models.Country", "Country")
                        .WithMany("AirPorts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.Country", b =>
                {
                    b.Navigation("AirPorts");
                });
#pragma warning restore 612, 618
        }
    }
}
