// <auto-generated />
using System;
using AirFlight2.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirFlight2.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240604100239_initial3")]
    partial class initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirFlight2.Entities.Models.AirPort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AirPortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("AirPorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirPortName = "Şakirpaşa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4701)
                        },
                        new
                        {
                            Id = 2,
                            AirPortName = "Ankara Esenboğa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4712)
                        },
                        new
                        {
                            Id = 3,
                            AirPortName = "Antalya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4713)
                        },
                        new
                        {
                            Id = 4,
                            AirPortName = "Gazipaşa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4715)
                        },
                        new
                        {
                            Id = 5,
                            AirPortName = "Balıkesir Koca Seyit Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4716)
                        },
                        new
                        {
                            Id = 6,
                            AirPortName = "Bursa Yenişehir Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4717)
                        },
                        new
                        {
                            Id = 7,
                            AirPortName = "Çanakkale Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4718)
                        },
                        new
                        {
                            Id = 8,
                            AirPortName = "Denizli Çardak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4719)
                        },
                        new
                        {
                            Id = 9,
                            AirPortName = "Diyarbakır Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4720)
                        },
                        new
                        {
                            Id = 10,
                            AirPortName = "Elazığ Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4756)
                        },
                        new
                        {
                            Id = 11,
                            AirPortName = "Erzurum Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4757)
                        },
                        new
                        {
                            Id = 12,
                            AirPortName = "Hasan Polatkan Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4758)
                        },
                        new
                        {
                            Id = 13,
                            AirPortName = "Gaziantep Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4759)
                        },
                        new
                        {
                            Id = 14,
                            AirPortName = "Hatay Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4760)
                        },
                        new
                        {
                            Id = 15,
                            AirPortName = "Isparta Süleyman Demirel Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4761)
                        },
                        new
                        {
                            Id = 16,
                            AirPortName = "İstanbul Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4763)
                        },
                        new
                        {
                            Id = 17,
                            AirPortName = "Sabiha Gökçen Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4764)
                        },
                        new
                        {
                            Id = 18,
                            AirPortName = "Adnan Menderes Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4765)
                        },
                        new
                        {
                            Id = 19,
                            AirPortName = "Kars Harakani Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4766)
                        },
                        new
                        {
                            Id = 20,
                            AirPortName = "Erkilet Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4767)
                        },
                        new
                        {
                            Id = 21,
                            AirPortName = "Cengiz Topel Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4768)
                        },
                        new
                        {
                            Id = 22,
                            AirPortName = "Konya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4769)
                        },
                        new
                        {
                            Id = 23,
                            AirPortName = "Zafer Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4770)
                        },
                        new
                        {
                            Id = 24,
                            AirPortName = "Malatya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4771)
                        },
                        new
                        {
                            Id = 25,
                            AirPortName = "Dalaman Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4772)
                        },
                        new
                        {
                            Id = 26,
                            AirPortName = "Milas-Bodrum Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4773)
                        },
                        new
                        {
                            Id = 27,
                            AirPortName = "Nevşehir Kapadokya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4774)
                        },
                        new
                        {
                            Id = 28,
                            AirPortName = "Ordu-Giresun Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4775)
                        },
                        new
                        {
                            Id = 29,
                            AirPortName = "Rize-Artvin Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4776)
                        },
                        new
                        {
                            Id = 30,
                            AirPortName = "Samsun Çarşamba Havalimanı	",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4777)
                        },
                        new
                        {
                            Id = 31,
                            AirPortName = "Sinop Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4778)
                        },
                        new
                        {
                            Id = 32,
                            AirPortName = "Sivas Nuri Demirağ Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4779)
                        },
                        new
                        {
                            Id = 33,
                            AirPortName = "Şanlıurfa GAP Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4780)
                        },
                        new
                        {
                            Id = 34,
                            AirPortName = "Tekirdağ Çorlu Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4781)
                        },
                        new
                        {
                            Id = 35,
                            AirPortName = "Trabzon Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4782)
                        },
                        new
                        {
                            Id = 36,
                            AirPortName = "Uşak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4784)
                        },
                        new
                        {
                            Id = 37,
                            AirPortName = "Van Ferit Melen Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4785)
                        },
                        new
                        {
                            Id = 38,
                            AirPortName = "Zonguldak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4786)
                        },
                        new
                        {
                            Id = 39,
                            AirPortName = "Merzbrück Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4787)
                        },
                        new
                        {
                            Id = 40,
                            AirPortName = "Leipzig-Altenburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4788)
                        },
                        new
                        {
                            Id = 41,
                            AirPortName = "Augsburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4789)
                        },
                        new
                        {
                            Id = 42,
                            AirPortName = "Baden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4790)
                        },
                        new
                        {
                            Id = 43,
                            AirPortName = "Berlin Schönefeld Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4791)
                        },
                        new
                        {
                            Id = 44,
                            AirPortName = "Berlin Tegel Havalimanı ",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4792)
                        },
                        new
                        {
                            Id = 45,
                            AirPortName = "Bindlacher Berg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4793)
                        },
                        new
                        {
                            Id = 46,
                            AirPortName = "Borkum Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4794)
                        },
                        new
                        {
                            Id = 47,
                            AirPortName = "Braunschweig Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4795)
                        },
                        new
                        {
                            Id = 48,
                            AirPortName = "Bremerhaven Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4796)
                        },
                        new
                        {
                            Id = 49,
                            AirPortName = "Dortmund Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4797)
                        },
                        new
                        {
                            Id = 50,
                            AirPortName = "Dresden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4798)
                        },
                        new
                        {
                            Id = 51,
                            AirPortName = "Düsseldorf Uluslararası Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4799)
                        },
                        new
                        {
                            Id = 52,
                            AirPortName = "Düsseldorf-Mönchengladbach Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4801)
                        },
                        new
                        {
                            Id = 53,
                            AirPortName = "Frankfurt Egelsbach Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4802)
                        },
                        new
                        {
                            Id = 54,
                            AirPortName = "Emden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4803)
                        },
                        new
                        {
                            Id = 55,
                            AirPortName = "Erfurt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4804)
                        },
                        new
                        {
                            Id = 56,
                            AirPortName = "Frankfurt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4805)
                        },
                        new
                        {
                            Id = 57,
                            AirPortName = "Friedrichshafen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4806)
                        },
                        new
                        {
                            Id = 58,
                            AirPortName = "Giebelstadt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4807)
                        },
                        new
                        {
                            Id = 59,
                            AirPortName = "Frankfurt-Hahn Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4809)
                        },
                        new
                        {
                            Id = 60,
                            AirPortName = "Hamburg Finkenwerder Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4810)
                        },
                        new
                        {
                            Id = 61,
                            AirPortName = "Hamburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4811)
                        },
                        new
                        {
                            Id = 62,
                            AirPortName = "Hannover-Langenhagen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4812)
                        },
                        new
                        {
                            Id = 63,
                            AirPortName = "Heide-Büsum Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4814)
                        },
                        new
                        {
                            Id = 64,
                            AirPortName = "Uetersen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4815)
                        },
                        new
                        {
                            Id = 65,
                            AirPortName = "Helgoland Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4816)
                        },
                        new
                        {
                            Id = 66,
                            AirPortName = "Heringsdorf Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4817)
                        },
                        new
                        {
                            Id = 67,
                            AirPortName = "Hof-Plauen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4818)
                        },
                        new
                        {
                            Id = 68,
                            AirPortName = "Hoppstädten-Weiersbach Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4819)
                        },
                        new
                        {
                            Id = 69,
                            AirPortName = "Ingolstadt Manching Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4820)
                        },
                        new
                        {
                            Id = 70,
                            AirPortName = "Kassel Calden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4821)
                        },
                        new
                        {
                            Id = 71,
                            AirPortName = "Kiel Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4822)
                        },
                        new
                        {
                            Id = 72,
                            AirPortName = "Köln Bonn Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4823)
                        },
                        new
                        {
                            Id = 73,
                            AirPortName = "Black Forest Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4824)
                        },
                        new
                        {
                            Id = 74,
                            AirPortName = "Leipzig/Halle Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4825)
                        },
                        new
                        {
                            Id = 75,
                            AirPortName = "Lübeck Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4826)
                        },
                        new
                        {
                            Id = 76,
                            AirPortName = "Magdeburg-Cochstedt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4827)
                        },
                        new
                        {
                            Id = 77,
                            AirPortName = "Mainz-Finthen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4828)
                        },
                        new
                        {
                            Id = 78,
                            AirPortName = "Mannheim City Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4829)
                        },
                        new
                        {
                            Id = 79,
                            AirPortName = "Memmingen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4830)
                        },
                        new
                        {
                            Id = 80,
                            AirPortName = "Münih Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4831)
                        },
                        new
                        {
                            Id = 81,
                            AirPortName = "Münster Osnabrück Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4832)
                        },
                        new
                        {
                            Id = 82,
                            AirPortName = "Nannhousen Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4834)
                        },
                        new
                        {
                            Id = 83,
                            AirPortName = "Neubrandenburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4835)
                        },
                        new
                        {
                            Id = 84,
                            AirPortName = "Nürnberg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4836)
                        },
                        new
                        {
                            Id = 85,
                            AirPortName = "Paderborn Lippstadt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4837)
                        },
                        new
                        {
                            Id = 86,
                            AirPortName = "Rechlin-Lärz Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4838)
                        },
                        new
                        {
                            Id = 87,
                            AirPortName = "Rostock-Laage Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4839)
                        },
                        new
                        {
                            Id = 88,
                            AirPortName = "Saarbrücken Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4840)
                        },
                        new
                        {
                            Id = 89,
                            AirPortName = "Siegerland Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4841)
                        },
                        new
                        {
                            Id = 90,
                            AirPortName = "Stadtlohn-Vreden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4842)
                        },
                        new
                        {
                            Id = 91,
                            AirPortName = "Stuttgart Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4843)
                        },
                        new
                        {
                            Id = 92,
                            AirPortName = "Trier-Föhren Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4844)
                        },
                        new
                        {
                            Id = 93,
                            AirPortName = "Weeze Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4845)
                        },
                        new
                        {
                            Id = 94,
                            AirPortName = "Sylt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4846)
                        },
                        new
                        {
                            Id = 95,
                            AirPortName = "Zweibrücken Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4847)
                        },
                        new
                        {
                            Id = 96,
                            AirPortName = "Bremen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(4848)
                        });
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(6469),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(6472),
                            Name = "USA"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 13, 2, 39, 513, DateTimeKind.Local).AddTicks(6473),
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.AirPort", b =>
                {
                    b.HasOne("AirFlight2.Entities.Models.Country", "Country")
                        .WithMany("AirPorts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.Country", b =>
                {
                    b.Navigation("AirPorts");
                });
#pragma warning restore 612, 618
        }
    }
}
