// <auto-generated />
using System;
using AirFlight2.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirFlight2.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirFlight2.Entities.Models.AirPort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AirPortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("AirPorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirPortName = "Şakirpaşa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8886)
                        },
                        new
                        {
                            Id = 2,
                            AirPortName = "Ankara Esenboğa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8899)
                        },
                        new
                        {
                            Id = 3,
                            AirPortName = "Antalya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8900)
                        },
                        new
                        {
                            Id = 4,
                            AirPortName = "Gazipaşa Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8902)
                        },
                        new
                        {
                            Id = 5,
                            AirPortName = "Balıkesir Koca Seyit Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8903)
                        },
                        new
                        {
                            Id = 6,
                            AirPortName = "Bursa Yenişehir Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8905)
                        },
                        new
                        {
                            Id = 7,
                            AirPortName = "Çanakkale Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8907)
                        },
                        new
                        {
                            Id = 8,
                            AirPortName = "Denizli Çardak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8908)
                        },
                        new
                        {
                            Id = 9,
                            AirPortName = "Diyarbakır Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8910)
                        },
                        new
                        {
                            Id = 10,
                            AirPortName = "Elazığ Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8912)
                        },
                        new
                        {
                            Id = 11,
                            AirPortName = "Erzurum Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8913)
                        },
                        new
                        {
                            Id = 12,
                            AirPortName = "Hasan Polatkan Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8915)
                        },
                        new
                        {
                            Id = 13,
                            AirPortName = "Gaziantep Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8916)
                        },
                        new
                        {
                            Id = 14,
                            AirPortName = "Hatay Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8918)
                        },
                        new
                        {
                            Id = 15,
                            AirPortName = "Isparta Süleyman Demirel Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8920)
                        },
                        new
                        {
                            Id = 16,
                            AirPortName = "İstanbul Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8921)
                        },
                        new
                        {
                            Id = 17,
                            AirPortName = "Sabiha Gökçen Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8923)
                        },
                        new
                        {
                            Id = 18,
                            AirPortName = "Adnan Menderes Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8924)
                        },
                        new
                        {
                            Id = 19,
                            AirPortName = "Kars Harakani Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8926)
                        },
                        new
                        {
                            Id = 20,
                            AirPortName = "Erkilet Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8927)
                        },
                        new
                        {
                            Id = 21,
                            AirPortName = "Cengiz Topel Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8929)
                        },
                        new
                        {
                            Id = 22,
                            AirPortName = "Konya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8931)
                        },
                        new
                        {
                            Id = 23,
                            AirPortName = "Zafer Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8932)
                        },
                        new
                        {
                            Id = 24,
                            AirPortName = "Malatya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8934)
                        },
                        new
                        {
                            Id = 25,
                            AirPortName = "Dalaman Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8935)
                        },
                        new
                        {
                            Id = 26,
                            AirPortName = "Milas-Bodrum Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8937)
                        },
                        new
                        {
                            Id = 27,
                            AirPortName = "Nevşehir Kapadokya Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8938)
                        },
                        new
                        {
                            Id = 28,
                            AirPortName = "Ordu-Giresun Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8940)
                        },
                        new
                        {
                            Id = 29,
                            AirPortName = "Rize-Artvin Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8942)
                        },
                        new
                        {
                            Id = 30,
                            AirPortName = "Samsun Çarşamba Havalimanı	",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8943)
                        },
                        new
                        {
                            Id = 31,
                            AirPortName = "Sinop Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8945)
                        },
                        new
                        {
                            Id = 32,
                            AirPortName = "Sivas Nuri Demirağ Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8946)
                        },
                        new
                        {
                            Id = 33,
                            AirPortName = "Şanlıurfa GAP Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8948)
                        },
                        new
                        {
                            Id = 34,
                            AirPortName = "Tekirdağ Çorlu Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8950)
                        },
                        new
                        {
                            Id = 35,
                            AirPortName = "Trabzon Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8952)
                        },
                        new
                        {
                            Id = 36,
                            AirPortName = "Uşak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(8953)
                        },
                        new
                        {
                            Id = 37,
                            AirPortName = "Van Ferit Melen Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9004)
                        },
                        new
                        {
                            Id = 38,
                            AirPortName = "Zonguldak Havalimanı",
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9006)
                        },
                        new
                        {
                            Id = 39,
                            AirPortName = "Merzbrück Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9008)
                        },
                        new
                        {
                            Id = 40,
                            AirPortName = "Leipzig-Altenburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9009)
                        },
                        new
                        {
                            Id = 41,
                            AirPortName = "Augsburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9011)
                        },
                        new
                        {
                            Id = 42,
                            AirPortName = "Baden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9013)
                        },
                        new
                        {
                            Id = 43,
                            AirPortName = "Berlin Schönefeld Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9014)
                        },
                        new
                        {
                            Id = 44,
                            AirPortName = "Berlin Tegel Havalimanı ",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9016)
                        },
                        new
                        {
                            Id = 45,
                            AirPortName = "Bindlacher Berg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9018)
                        },
                        new
                        {
                            Id = 46,
                            AirPortName = "Borkum Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9019)
                        },
                        new
                        {
                            Id = 47,
                            AirPortName = "Braunschweig Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9021)
                        },
                        new
                        {
                            Id = 48,
                            AirPortName = "Bremerhaven Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9023)
                        },
                        new
                        {
                            Id = 49,
                            AirPortName = "Dortmund Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9024)
                        },
                        new
                        {
                            Id = 50,
                            AirPortName = "Dresden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9026)
                        },
                        new
                        {
                            Id = 51,
                            AirPortName = "Düsseldorf Uluslararası Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9027)
                        },
                        new
                        {
                            Id = 52,
                            AirPortName = "Düsseldorf-Mönchengladbach Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9029)
                        },
                        new
                        {
                            Id = 53,
                            AirPortName = "Frankfurt Egelsbach Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9030)
                        },
                        new
                        {
                            Id = 54,
                            AirPortName = "Emden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9032)
                        },
                        new
                        {
                            Id = 55,
                            AirPortName = "Erfurt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9033)
                        },
                        new
                        {
                            Id = 56,
                            AirPortName = "Frankfurt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9035)
                        },
                        new
                        {
                            Id = 57,
                            AirPortName = "Friedrichshafen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9037)
                        },
                        new
                        {
                            Id = 58,
                            AirPortName = "Giebelstadt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9038)
                        },
                        new
                        {
                            Id = 59,
                            AirPortName = "Frankfurt-Hahn Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9040)
                        },
                        new
                        {
                            Id = 60,
                            AirPortName = "Hamburg Finkenwerder Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9041)
                        },
                        new
                        {
                            Id = 61,
                            AirPortName = "Hamburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9043)
                        },
                        new
                        {
                            Id = 62,
                            AirPortName = "Hannover-Langenhagen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9044)
                        },
                        new
                        {
                            Id = 63,
                            AirPortName = "Heide-Büsum Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9046)
                        },
                        new
                        {
                            Id = 64,
                            AirPortName = "Uetersen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9048)
                        },
                        new
                        {
                            Id = 65,
                            AirPortName = "Helgoland Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9049)
                        },
                        new
                        {
                            Id = 66,
                            AirPortName = "Heringsdorf Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9051)
                        },
                        new
                        {
                            Id = 67,
                            AirPortName = "Hof-Plauen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9052)
                        },
                        new
                        {
                            Id = 68,
                            AirPortName = "Hoppstädten-Weiersbach Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9054)
                        },
                        new
                        {
                            Id = 69,
                            AirPortName = "Ingolstadt Manching Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9056)
                        },
                        new
                        {
                            Id = 70,
                            AirPortName = "Kassel Calden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9057)
                        },
                        new
                        {
                            Id = 71,
                            AirPortName = "Kiel Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9059)
                        },
                        new
                        {
                            Id = 72,
                            AirPortName = "Köln Bonn Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9060)
                        },
                        new
                        {
                            Id = 73,
                            AirPortName = "Black Forest Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9062)
                        },
                        new
                        {
                            Id = 74,
                            AirPortName = "Leipzig/Halle Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9063)
                        },
                        new
                        {
                            Id = 75,
                            AirPortName = "Lübeck Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9065)
                        },
                        new
                        {
                            Id = 76,
                            AirPortName = "Magdeburg-Cochstedt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9066)
                        },
                        new
                        {
                            Id = 77,
                            AirPortName = "Mainz-Finthen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9068)
                        },
                        new
                        {
                            Id = 78,
                            AirPortName = "Mannheim City Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9070)
                        },
                        new
                        {
                            Id = 79,
                            AirPortName = "Memmingen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9071)
                        },
                        new
                        {
                            Id = 80,
                            AirPortName = "Münih Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9074)
                        },
                        new
                        {
                            Id = 81,
                            AirPortName = "Münster Osnabrück Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9075)
                        },
                        new
                        {
                            Id = 82,
                            AirPortName = "Nannhousen Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9077)
                        },
                        new
                        {
                            Id = 83,
                            AirPortName = "Neubrandenburg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9078)
                        },
                        new
                        {
                            Id = 84,
                            AirPortName = "Nürnberg Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9080)
                        },
                        new
                        {
                            Id = 85,
                            AirPortName = "Paderborn Lippstadt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9081)
                        },
                        new
                        {
                            Id = 86,
                            AirPortName = "Rechlin-Lärz Havaalanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9083)
                        },
                        new
                        {
                            Id = 87,
                            AirPortName = "Rostock-Laage Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9084)
                        },
                        new
                        {
                            Id = 88,
                            AirPortName = "Saarbrücken Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9086)
                        },
                        new
                        {
                            Id = 89,
                            AirPortName = "Siegerland Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9088)
                        },
                        new
                        {
                            Id = 90,
                            AirPortName = "Stadtlohn-Vreden Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9089)
                        },
                        new
                        {
                            Id = 91,
                            AirPortName = "Stuttgart Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9091)
                        },
                        new
                        {
                            Id = 92,
                            AirPortName = "Trier-Föhren Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9092)
                        },
                        new
                        {
                            Id = 93,
                            AirPortName = "Weeze Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9094)
                        },
                        new
                        {
                            Id = 94,
                            AirPortName = "Sylt Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9096)
                        },
                        new
                        {
                            Id = 95,
                            AirPortName = "Zweibrücken Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9098)
                        },
                        new
                        {
                            Id = 96,
                            AirPortName = "Bremen Havalimanı",
                            CountryId = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9099)
                        },
                        new
                        {
                            Id = 97,
                            AirPortName = "Atlanta",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9101)
                        },
                        new
                        {
                            Id = 98,
                            AirPortName = "Chicago O’Hare",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9103)
                        },
                        new
                        {
                            Id = 99,
                            AirPortName = "Los Angeles",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9104)
                        },
                        new
                        {
                            Id = 100,
                            AirPortName = "Denver",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9106)
                        },
                        new
                        {
                            Id = 101,
                            AirPortName = "Dallas/Fort Worth	",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9108)
                        },
                        new
                        {
                            Id = 102,
                            AirPortName = "New York JFK",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9109)
                        },
                        new
                        {
                            Id = 103,
                            AirPortName = "San Francisco",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9111)
                        },
                        new
                        {
                            Id = 104,
                            AirPortName = "Las Vegas",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9112)
                        },
                        new
                        {
                            Id = 105,
                            AirPortName = "Charlotte",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9114)
                        },
                        new
                        {
                            Id = 106,
                            AirPortName = "Houston Bush",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9115)
                        },
                        new
                        {
                            Id = 107,
                            AirPortName = "Miami",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9117)
                        },
                        new
                        {
                            Id = 108,
                            AirPortName = "Phoenix",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9118)
                        },
                        new
                        {
                            Id = 109,
                            AirPortName = "Orlando",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9120)
                        },
                        new
                        {
                            Id = 110,
                            AirPortName = "Seattle",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9121)
                        },
                        new
                        {
                            Id = 111,
                            AirPortName = "Minneapolis/St",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9123)
                        },
                        new
                        {
                            Id = 112,
                            AirPortName = "Newark",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9124)
                        },
                        new
                        {
                            Id = 113,
                            AirPortName = "Philadelphia",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9126)
                        },
                        new
                        {
                            Id = 114,
                            AirPortName = "Boston",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9128)
                        },
                        new
                        {
                            Id = 115,
                            AirPortName = "",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9129)
                        },
                        new
                        {
                            Id = 116,
                            AirPortName = "New York LaGuardia",
                            CountryId = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 660, DateTimeKind.Local).AddTicks(9131)
                        });
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 661, DateTimeKind.Local).AddTicks(1091),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 661, DateTimeKind.Local).AddTicks(1096),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 10, 14, 39, 6, 661, DateTimeKind.Local).AddTicks(1098),
                            Name = "USA"
                        });
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.AirPort", b =>
                {
                    b.HasOne("AirFlight2.Entities.Models.Country", "Country")
                        .WithMany("AirPorts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AirFlight2.Entities.Models.Country", b =>
                {
                    b.Navigation("AirPorts");
                });
#pragma warning restore 612, 618
        }
    }
}
